AllCops:
  Exclude:
    - "topiary.gemspec"
    - "vendor/**/*"

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/ExtraSpacing:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
  ExcludedMethods: describe
  Max: 30

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - "spec/**/*"
  Max: 35

Metrics/ClassLength:
  Max: 1000

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: line_count_based
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Exclude:
    - "spec/**/*"

Style/SafeNavigation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"

Style/NegatedWhile:
  Enabled: false

Style/Not:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Naming/UncommunicativeMethodParamName:
  Enabled: false

Lint/EmptyWhen:
  Enabled: false
